#define BLOCK_MULT_FUNC
#define RIGHT_TRANSPOSE
// #define USE_REDUCTION
#define USE_SIMD

#define UNROLL_DISABLED 0
#define UNROLL_NORMAL 1
#define UNROLL_HARD 2

// #define UNROLLED_SIMD UNROLL_DISABLED
// #define UNROLLED_SIMD UNROLL_NORMAL
#define UNROLLED_SIMD UNROLL_HARD

#define INNER_TYPE double
#define CACHE_SIZE 0x100
#define INDEX_TYPE int

#define PARALLEL 0x18

#define SUPER_SIZE (MATRIX_SIZE / BLOCK_SIZE)

#define BLOCK_SIZE 0x10
#define MATRIX_SIZE 0x100

#define SIMD_TYPE __m256d
#define SIMD_WIDTH (sizeof(SIMD_TYPE) / sizeof(INNER_TYPE))
#define SIMD_PER_BLOCK (BLOCK_SIZE / SIMD_WIDTH)
